#!/bin/sh
#
# convert .sql files into a header string constant
# 
# usage: gen_sql_headers.sh <sql_dir> <output.h>
# 

set -e

sql_dir="$1"
output="$2"

guard="$(echo "$output" | sed 's/[^a-zA-Z0-9]/_/g' | tr '[:lower:]' '[:upper:]')_"

{
	echo "/* generated by gen_sql_headers.sh — do not edit! */"
	echo "#ifndef $guard"
	echo "#define $guard"
	echo ""
	for f in "$sql_dir"/*.sql; do
		[ -f "$f" ] || continue
		name=$(basename "$f" .sql)
		echo "static const char *sql_${name} ="
		sed 's/\\/\\\\/g; s/"/\\"/g; s/^/\t"/; s/$/\\n"/' "$f"
		echo ";"
		echo ""
	done
	echo "#endif /* $guard */"
} > "$output"
