use std::io::Write;

use crate::commands::MigrationStep;
use crate::OutputFormat;

pub fn emit(steps: &[MigrationStep], format: &OutputFormat) {
    match format {
        OutputFormat::Sql => emit_sql(steps),
        OutputFormat::Plain => emit_plain(steps),
    }
}

fn emit_sql(steps: &[MigrationStep]) {
    let stdout = std::io::stdout();
    let mut out = stdout.lock();
    for step in steps {
        writeln!(out, "{};\n", step.sql.trim_end_matches(';').trim_end()).unwrap();
    }
}

fn emit_plain(steps: &[MigrationStep]) {
    let mut buf = String::from("-- Generated by pg_viewctl\n");
    for step in steps {
        buf.push_str(&format!(
            "\n-- Step {}: {}\n{};\n",
            step.step,
            step.operation,
            step.sql.trim_end_matches(';').trim_end()
        ));
    }

    std::fs::write("up.sql", &buf).unwrap();

    let down_buf = generate_down(steps);
    std::fs::write("down.sql", &down_buf).unwrap();

    eprintln!(
        "Wrote {} steps to up.sql + down.sql",
        steps.len()
    );
}

fn generate_down(steps: &[MigrationStep]) -> String {
    let mut lines = vec!["-- Generated by pg_viewctl (rollback)".to_string()];
    let mut step_num = 1;

    for step in steps.iter().rev() {
        let op = &step.operation;
        let clean_sql = strip_trailing_semicolon(&step.sql);

        if is_drop(op) {
            let name = extract_object_name(&step.sql);
            let create_sql = find_create_sql_for(&name, steps);
            if create_sql.is_empty() {
                lines.push(format!(
                    "\n-- Step {}: TODO: recreate {} (definition not found)",
                    step_num, name
                ));
            } else {
                lines.push(format!("\n-- Step {}: recreate {}", step_num, name));
                lines.push(format!("{};", strip_trailing_semicolon(&create_sql)));
            }
        } else if is_create(op) {
            let name = extract_object_name(&step.sql);
            let drop_kind = if op.contains("MATERIALIZED") {
                "MATERIALIZED VIEW"
            } else {
                "VIEW"
            };
            lines.push(format!("\n-- Step {}: drop {}", step_num, name));
            lines.push(format!("DROP {} IF EXISTS {} CASCADE;", drop_kind, name));
        } else if op.starts_with("ALTER TABLE") {
            lines.push(format!("\n-- Step {}: TODO: reverse this manually", step_num));
            lines.push(format!("-- {};", clean_sql));
        } else {
            lines.push(format!("\n-- Step {}: {}", step_num, op));
            lines.push(format!("{};", clean_sql));
        }

        step_num += 1;
    }

    lines.push(String::new()); // trailing newline
    lines.join("\n")
}

fn is_drop(operation: &str) -> bool {
    operation.starts_with("DROP VIEW") || operation.starts_with("DROP MATERIALIZED VIEW")
}

fn is_create(operation: &str) -> bool {
    operation.starts_with("CREATE VIEW")
        || operation.starts_with("CREATE MATERIALIZED VIEW")
        || operation.starts_with("CREATE OR REPLACE")
}

fn find_create_sql_for(object_name: &str, steps: &[MigrationStep]) -> String {
    for step in steps {
        if is_create(&step.operation) && extract_object_name(&step.sql) == object_name {
            return step.sql.clone();
        }
    }
    String::new()
}

fn strip_trailing_semicolon(sql: &str) -> String {
    sql.trim_end().trim_end_matches(';').trim_end().to_string()
}

/// "CREATE OR REPLACE VIEW public.my_view AS ..." to "public.my_view"
/// "DROP VIEW IF EXISTS public.my_view CASCADE" to "public.my_view"
fn extract_object_name(sql: &str) -> String {
    let skip_words = [
        "DROP", "CREATE", "OR", "REPLACE", "MATERIALIZED", "VIEW", "IF", "EXISTS", "CASCADE",
    ];

    for word in sql.split_whitespace() {
        let normalized = word.trim_end_matches('(').to_uppercase();
        if skip_words.contains(&normalized.as_str()) {
            continue;
        }
        return word.trim_end_matches('(').to_string();
    }

    String::new()
}
