use std::io::Write;

use crate::commands::MigrationStep;
use crate::OutputFormat;

pub fn emit(steps: &[MigrationStep], format: &OutputFormat) {
    match format {
        OutputFormat::Sql => emit_sql(steps),
        OutputFormat::Plain => emit_plain(steps),
    }
}

fn emit_sql(steps: &[MigrationStep]) {
    let stdout = std::io::stdout();
    let mut out = stdout.lock();
    for step in steps {
        writeln!(out, "{};\n", step.sql.trim_end_matches(';').trim_end()).unwrap();
    }
}

fn emit_plain(steps: &[MigrationStep]) {
    let mut buf = String::from("-- Generated by pg_viewctl\n");
    for step in steps {
        buf.push_str(&format!(
            "\n-- Step {}: {}\n{};\n",
            step.step,
            step.operation,
            step.sql.trim_end_matches(';').trim_end()
        ));
    }

    std::fs::write("up.sql", &buf).unwrap();
    eprintln!("Wrote {} steps to up.sql", steps.len());
}
