use std::io::Write;

use chrono::Utc;

use crate::commands::MigrationStep;
use crate::OutputFormat;

pub fn emit(steps: &[MigrationStep], format: &OutputFormat, operation_name: &str) {
    match format {
        OutputFormat::Sql => emit_sql(steps),
        OutputFormat::Plain => emit_plain(steps),
        OutputFormat::Goose => emit_goose(steps, operation_name),
    }
}

fn emit_sql(steps: &[MigrationStep]) {
    let stdout = std::io::stdout();
    let mut out = stdout.lock();
    for step in steps {
        writeln!(out, "{};\n", step.sql.trim_end_matches(';').trim_end()).unwrap();
    }
}

fn emit_plain(steps: &[MigrationStep]) {
    let mut buf = String::from("-- Generated by pg_viewctl\n");
    for step in steps {
        buf.push_str(&format!(
            "\n-- Step {}: {}\n{};\n",
            step.step,
            step.operation,
            step.sql.trim_end_matches(';').trim_end()
        ));
    }

    std::fs::write("up.sql", &buf).unwrap();

    let down_buf = generate_down(steps);
    std::fs::write("down.sql", &down_buf).unwrap();

    eprintln!(
        "Wrote {} steps to up.sql + down.sql",
        steps.len()
    );
}

fn emit_goose(steps: &[MigrationStep], operation_name: &str) {
    let mut buf = String::from("-- +goose Up\n");

    for step in steps {
        let clean = strip_trailing_semicolon(&step.sql);
        buf.push('\n');
        write_goose_statement(&mut buf, &format!("{};\n", clean));
    }

    buf.push_str("\n-- +goose Down\n");

    for (comment, sql) in invert_steps(steps) {
        buf.push('\n');
        let stmt = match comment {
            Some(c) => format!("-- {}\n{};\n", c, strip_trailing_semicolon(&sql)),
            None => format!("{};\n", strip_trailing_semicolon(&sql)),
        };
        write_goose_statement(&mut buf, &stmt);
    }

    let ts = Utc::now().format("%Y%m%d%H%M%S");
    let filename = format!("{}_{}.sql", ts, operation_name);
    std::fs::write(&filename, &buf).unwrap();

    eprintln!("Wrote goose migration to {}", filename);
}

fn needs_statement_block(sql: &str) -> bool {
    sql.contains("$$")
}

fn write_goose_statement(buf: &mut String, stmt: &str) {
    if needs_statement_block(stmt) {
        buf.push_str("-- +goose StatementBegin\n");
        buf.push_str(stmt);
        buf.push_str("-- +goose StatementEnd\n");
    } else {
        buf.push_str(stmt);
    }
}

fn invert_steps(steps: &[MigrationStep]) -> Vec<(Option<String>, String)> {
    let mut result = Vec::new();

    for step in steps.iter().rev() {
        let op = &step.operation;
        let clean_sql = strip_trailing_semicolon(&step.sql);

        if is_drop(op) {
            let name = extract_object_name(&step.sql);
            let create_sql = find_create_sql_for(&name, steps);
            if create_sql.is_empty() {
                result.push((
                    Some(format!("TODO: recreate {} (definition not found)", name)),
                    format!("SELECT 1 /* placeholder for {} */", name),
                ));
            } else {
                let stripped = strip_leading_comments(&create_sql);
                result.push((
                    Some(format!("recreate {}", name)),
                    strip_trailing_semicolon(&stripped),
                ));
            }
        } else if is_create(op) {
            let name = extract_object_name(&step.sql);
            let drop_kind = if op.contains("MATERIALIZED") {
                "MATERIALIZED VIEW"
            } else {
                "VIEW"
            };
            result.push((
                Some(format!("drop {}", name)),
                format!("DROP {} IF EXISTS {} CASCADE", drop_kind, name),
            ));
        } else if op.starts_with("ALTER TABLE") {
            result.push((
                Some("TODO: reverse this manually".to_string()),
                format!("/* {} */", clean_sql),
            ));
        } else {
            result.push((None, clean_sql));
        }
    }

    result
}

fn generate_down(steps: &[MigrationStep]) -> String {
    let mut lines = vec!["-- Generated by pg_viewctl (rollback)".to_string()];

    for (i, (comment, sql)) in invert_steps(steps).iter().enumerate() {
        let label = match comment {
            Some(c) => c.clone(),
            None => sql.split_whitespace().take(4).collect::<Vec<_>>().join(" "),
        };
        lines.push(format!("\n-- Step {}: {}", i + 1, label));
        lines.push(format!("{};", sql));
    }

    lines.push(String::new());
    lines.join("\n")
}

fn is_drop(operation: &str) -> bool {
    operation.starts_with("DROP VIEW") || operation.starts_with("DROP MATERIALIZED VIEW")
}

fn is_create(operation: &str) -> bool {
    operation.starts_with("CREATE VIEW")
        || operation.starts_with("CREATE MATERIALIZED VIEW")
        || operation.starts_with("CREATE OR REPLACE")
}

fn find_create_sql_for(object_name: &str, steps: &[MigrationStep]) -> String {
    for step in steps {
        if is_create(&step.operation) && extract_object_name(&step.sql) == object_name {
            return step.sql.clone();
        }
    }
    String::new()
}

fn strip_leading_comments(sql: &str) -> String {
    sql.lines()
        .skip_while(|l| l.trim_start().starts_with("--"))
        .collect::<Vec<_>>()
        .join("\n")
}

fn strip_trailing_semicolon(sql: &str) -> String {
    sql.trim_end().trim_end_matches(';').trim_end().to_string()
}

/// "CREATE OR REPLACE VIEW public.my_view AS ..." to "public.my_view"
/// "DROP VIEW IF EXISTS public.my_view CASCADE" to "public.my_view"
fn extract_object_name(sql: &str) -> String {
    let skip_words = [
        "DROP", "CREATE", "OR", "REPLACE", "MATERIALIZED", "VIEW", "IF", "EXISTS", "CASCADE",
    ];

    // skip leading SQL comment lines
    let effective = sql
        .lines()
        .find(|l| !l.trim_start().starts_with("--"))
        .unwrap_or("");

    for word in effective.split_whitespace() {
        let clean = word.trim_end_matches('(');
        let normalized = clean.replace('"', "").to_uppercase();
        if skip_words.contains(&normalized.as_str()) {
            continue;
        }
        // strip quotes so "hr"."v_foo" and hr.v_foo match
        return clean.replace('"', "");
    }

    String::new()
}
